currencies_mapping = [
                    ("INR", "🇮🇳 Indian Rupee (₹)"),
                    ("USD", "🇺🇸 US Dollar ($)"),
                    ("EUR", "🇪🇺 Euro (€)"),
                    ("GBP", "🇬🇧 British Pound (£)"),
                    ("JPY", "🇯🇵 Japanese Yen (¥)"),
                    ("CAD", "🇨🇦 Canadian Dollar (C$)"),
                    ("AUD", "🇦🇺 Australian Dollar (A$)"),
                    ("CHF", "🇨🇭 Swiss Franc (CHF)"),
                    ("BRL", "🇧🇷 Brazilian Real (R$)"),
                    ("MXN", "🇲🇽 Mexican Peso ($)"),
                    ("SGD", "🇸🇬 Singapore Dollar (S$)"),
                    ("HKD", "🇭🇰 Hong Kong Dollar (HK$)"),
                    ("NZD", "🇳🇿 New Zealand Dollar (NZ$)"),
                    ("CNY", "🇨🇳 Chinese Yuan (¥)"),
                    ("KRW", "🇰🇷 South Korean Won (₩)"),
                    ("THB", "🇹🇭 Thai Baht (฿)"),
                    ("MYR", "🇲🇾 Malaysian Ringgit (RM)"),
                    ("IDR", "🇮🇩 Indonesian Rupiah (Rp)"),
                    ("PHP", "🇵🇭 Philippine Peso (₱)"),
                    ("VND", "🇻🇳 Vietnamese Dong (₫)"),
                    ("TRY", "🇹🇷 Turkish Lira (₺)"),
                    ("AED", "🇦🇪 UAE Dirham (د.إ)"),
                    ("SAR", "🇸🇦 Saudi Riyal (ر.س)"),
                    ("ILS", "🇮🇱 Israeli Shekel (₪)"),
                    ("QAR", "🇶🇦 Qatari Riyal (ر.ق)"),
                    ("KWD", "🇰🇼 Kuwaiti Dinar (د.ك)"),
                    ("BHD", "🇧🇭 Bahraini Dinar (د.ب)"),
                    ("OMR", "🇴🇲 Omani Rial (ر.ع.)"),
                    ("JOD", "🇯🇴 Jordanian Dinar (د.ا)"),
                    ("LBP", "🇱🇧 Lebanese Pound (ل.ل)"),
                    ("PKR", "🇵🇰 Pakistani Rupee (₨)"),
                    ("BDT", "🇧🇩 Bangladeshi Taka (৳)"),
                    ("LKR", "🇱🇰 Sri Lankan Rupee (₨)"),
                    ("NPR", "🇳🇵 Nepalese Rupee (₨)")
                ]

def get_currency_options():
    """Get list of popular currencies with their symbols and codes"""
    return {
        "USD": {"symbol": "$", "name": "US Dollar"},
        "EUR": {"symbol": "€", "name": "Euro"},
        "GBP": {"symbol": "£", "name": "British Pound"},
        "JPY": {"symbol": "¥", "name": "Japanese Yen"},
        "CAD": {"symbol": "C$", "name": "Canadian Dollar"},
        "AUD": {"symbol": "A$", "name": "Australian Dollar"},
        "CHF": {"symbol": "CHF", "name": "Swiss Franc"},
        "CNY": {"symbol": "¥", "name": "Chinese Yuan"},
        "INR": {"symbol": "₹", "name": "Indian Rupee"},
        "BRL": {"symbol": "R$", "name": "Brazilian Real"},
        "MXN": {"symbol": "$", "name": "Mexican Peso"},
        "SGD": {"symbol": "S$", "name": "Singapore Dollar"},
        "HKD": {"symbol": "HK$", "name": "Hong Kong Dollar"},
        "NZD": {"symbol": "NZ$", "name": "New Zealand Dollar"},
        "SEK": {"symbol": "kr", "name": "Swedish Krona"},
        "NOK": {"symbol": "kr", "name": "Norwegian Krone"},
        "DKK": {"symbol": "kr", "name": "Danish Krone"},
        "PLN": {"symbol": "zł", "name": "Polish Zloty"},
        "CZK": {"symbol": "Kč", "name": "Czech Koruna"},
        "HUF": {"symbol": "Ft", "name": "Hungarian Forint"},
        "RUB": {"symbol": "₽", "name": "Russian Ruble"},
        "ZAR": {"symbol": "R", "name": "South African Rand"},
        "KRW": {"symbol": "₩", "name": "South Korean Won"},
        "THB": {"symbol": "฿", "name": "Thai Baht"},
        "MYR": {"symbol": "RM", "name": "Malaysian Ringgit"},
        "IDR": {"symbol": "Rp", "name": "Indonesian Rupiah"},
        "PHP": {"symbol": "₱", "name": "Philippine Peso"},
        "VND": {"symbol": "₫", "name": "Vietnamese Dong"},
        "TRY": {"symbol": "₺", "name": "Turkish Lira"},
        "AED": {"symbol": "د.إ", "name": "UAE Dirham"},
        "SAR": {"symbol": "﷼", "name": "Saudi Riyal"},
        "EGP": {"symbol": "£", "name": "Egyptian Pound"},
        "ILS": {"symbol": "₪", "name": "Israeli Shekel"},
        "QAR": {"symbol": "﷼", "name": "Qatari Riyal"},
        "KWD": {"symbol": "د.ك", "name": "Kuwaiti Dinar"},
        "BHD": {"symbol": "د.ب", "name": "Bahraini Dinar"},
        "OMR": {"symbol": "﷼", "name": "Omani Rial"},
        "JOD": {"symbol": "د.ا", "name": "Jordanian Dinar"},
        "LBP": {"symbol": "ل.ل", "name": "Lebanese Pound"},
        "PKR": {"symbol": "₨", "name": "Pakistani Rupee"},
        "BDT": {"symbol": "৳", "name": "Bangladeshi Taka"},
        "LKR": {"symbol": "₨", "name": "Sri Lankan Rupee"},
        "NPR": {"symbol": "₨", "name": "Nepalese Rupee"},
        "AFN": {"symbol": "؋", "name": "Afghan Afghani"},
        "AMD": {"symbol": "֏", "name": "Armenian Dram"},
        "AZN": {"symbol": "₼", "name": "Azerbaijani Manat"},
        "GEL": {"symbol": "₾", "name": "Georgian Lari"},
        "KZT": {"symbol": "₸", "name": "Kazakhstani Tenge"},
        "KGS": {"symbol": "лв", "name": "Kyrgyzstani Som"},
        "TJS": {"symbol": "ЅМ", "name": "Tajikistani Somoni"},
        "TMT": {"symbol": "T", "name": "Turkmenistani Manat"},
        "UZS": {"symbol": "лв", "name": "Uzbekistani Som"},
        "MNT": {"symbol": "₮", "name": "Mongolian Tugrik"},
        "LAK": {"symbol": "₭", "name": "Lao Kip"},
        "KHR": {"symbol": "៛", "name": "Cambodian Riel"},
        "MMK": {"symbol": "K", "name": "Myanmar Kyat"},
        "BND": {"symbol": "B$", "name": "Brunei Dollar"},
        "FJD": {"symbol": "FJ$", "name": "Fijian Dollar"},
        "PGK": {"symbol": "K", "name": "Papua New Guinea Kina"},
        "SBD": {"symbol": "SI$", "name": "Solomon Islands Dollar"},
        "VUV": {"symbol": "Vt", "name": "Vanuatu Vatu"},
        "WST": {"symbol": "WS$", "name": "Samoan Tala"},
        "TOP": {"symbol": "T$", "name": "Tongan Pa'anga"},
        "XPF": {"symbol": "₣", "name": "CFP Franc"},
        "NPR": {"symbol": "₨", "name": "Nepalese Rupee"},
        "BTN": {"symbol": "Nu.", "name": "Bhutanese Ngultrum"},
        "MVR": {"symbol": "Rf", "name": "Maldivian Rufiyaa"},
        "SCR": {"symbol": "₨", "name": "Seychellois Rupee"},
        "MUR": {"symbol": "₨", "name": "Mauritian Rupee"},
        "KMF": {"symbol": "CF", "name": "Comorian Franc"},
        "DJF": {"symbol": "Fdj", "name": "Djiboutian Franc"},
        "ETB": {"symbol": "Br", "name": "Ethiopian Birr"},
        "KES": {"symbol": "KSh", "name": "Kenyan Shilling"},
        "TZS": {"symbol": "TSh", "name": "Tanzanian Shilling"},
        "UGX": {"symbol": "USh", "name": "Ugandan Shilling"},
        "RWF": {"symbol": "RF", "name": "Rwandan Franc"},
        "BIF": {"symbol": "FBu", "name": "Burundian Franc"},
        "MWK": {"symbol": "MK", "name": "Malawian Kwacha"},
        "ZMW": {"symbol": "ZK", "name": "Zambian Kwacha"},
        "BWP": {"symbol": "P", "name": "Botswana Pula"},
        "SZL": {"symbol": "L", "name": "Swazi Lilangeni"},
        "LSL": {"symbol": "L", "name": "Lesotho Loti"},
        "NAD": {"symbol": "N$", "name": "Namibian Dollar"},
        "MZN": {"symbol": "MT", "name": "Mozambican Metical"},
        "AOA": {"symbol": "Kz", "name": "Angolan Kwanza"},
        "XOF": {"symbol": "CFA", "name": "West African CFA Franc"},
        "XAF": {"symbol": "FCFA", "name": "Central African CFA Franc"},
        "CDF": {"symbol": "FC", "name": "Congolese Franc"},
        "GMD": {"symbol": "D", "name": "Gambian Dalasi"},
        "GHS": {"symbol": "₵", "name": "Ghanaian Cedi"},
        "GNF": {"symbol": "FG", "name": "Guinean Franc"},
        "LRD": {"symbol": "L$", "name": "Liberian Dollar"},
        "SLL": {"symbol": "Le", "name": "Sierra Leonean Leone"},
        "NGN": {"symbol": "₦", "name": "Nigerian Naira"},
        "XOF": {"symbol": "CFA", "name": "West African CFA Franc"},
        "XAF": {"symbol": "FCFA", "name": "Central African CFA Franc"},
        "TND": {"symbol": "د.ت", "name": "Tunisian Dinar"},
        "DZD": {"symbol": "د.ج", "name": "Algerian Dinar"},
        "MAD": {"symbol": "د.م.", "name": "Moroccan Dirham"},
        "LYD": {"symbol": "ل.د", "name": "Libyan Dinar"},
        "SDG": {"symbol": "ج.س.", "name": "Sudanese Pound"},
        "SSP": {"symbol": "£", "name": "South Sudanese Pound"},
        "ETB": {"symbol": "Br", "name": "Ethiopian Birr"},
        "SOS": {"symbol": "S", "name": "Somali Shilling"},
        "DJF": {"symbol": "Fdj", "name": "Djiboutian Franc"},
        "ERN": {"symbol": "Nfk", "name": "Eritrean Nakfa"},
        "SYP": {"symbol": "£", "name": "Syrian Pound"},
        "LBP": {"symbol": "ل.ل", "name": "Lebanese Pound"},
        "JOD": {"symbol": "د.ا", "name": "Jordanian Dinar"},
        "IQD": {"symbol": "ع.د", "name": "Iraqi Dinar"},
        "IRR": {"symbol": "﷼", "name": "Iranian Rial"},
        "YER": {"symbol": "﷼", "name": "Yemeni Rial"},
        "OMR": {"symbol": "﷼", "name": "Omani Rial"},
        "QAR": {"symbol": "﷼", "name": "Qatari Riyal"},
        "BHD": {"symbol": "د.ب", "name": "Bahraini Dinar"},
        "KWD": {"symbol": "د.ك", "name": "Kuwaiti Dinar"},
        "AED": {"symbol": "د.إ", "name": "UAE Dirham"},
        "SAR": {"symbol": "﷼", "name": "Saudi Riyal"},
        "ILS": {"symbol": "₪", "name": "Israeli Shekel"},
        "PAB": {"symbol": "B/.", "name": "Panamanian Balboa"},
        "CRC": {"symbol": "₡", "name": "Costa Rican Colón"},
        "GTQ": {"symbol": "Q", "name": "Guatemalan Quetzal"},
        "HNL": {"symbol": "L", "name": "Honduran Lempira"},
        "NIO": {"symbol": "C$", "name": "Nicaraguan Córdoba"},
        "PAB": {"symbol": "B/.", "name": "Panamanian Balboa"},
        "SVC": {"symbol": "₡", "name": "Salvadoran Colón"},
        "BZD": {"symbol": "BZ$", "name": "Belize Dollar"},
        "JMD": {"symbol": "J$", "name": "Jamaican Dollar"},
        "TTD": {"symbol": "TT$", "name": "Trinidad and Tobago Dollar"},
        "BBD": {"symbol": "Bds$", "name": "Barbadian Dollar"},
        "XCD": {"symbol": "EC$", "name": "East Caribbean Dollar"},
        "AWG": {"symbol": "ƒ", "name": "Aruban Florin"},
        "ANG": {"symbol": "ƒ", "name": "Netherlands Antillean Guilder"},
        "SRD": {"symbol": "$", "name": "Surinamese Dollar"},
        "GYD": {"symbol": "G$", "name": "Guyanese Dollar"},
        "VES": {"symbol": "Bs.S", "name": "Venezuelan Bolívar"},
        "COP": {"symbol": "$", "name": "Colombian Peso"},
        "PEN": {"symbol": "S/", "name": "Peruvian Sol"},
        "BOB": {"symbol": "Bs", "name": "Bolivian Boliviano"},
        "CLP": {"symbol": "$", "name": "Chilean Peso"},
        "ARS": {"symbol": "$", "name": "Argentine Peso"},
        "UYU": {"symbol": "$U", "name": "Uruguayan Peso"},
        "PYG": {"symbol": "₲", "name": "Paraguayan Guarani"},
        "BRL": {"symbol": "R$", "name": "Brazilian Real"},
        "FKP": {"symbol": "£", "name": "Falkland Islands Pound"},
        "GBP": {"symbol": "£", "name": "British Pound"},
        "EUR": {"symbol": "€", "name": "Euro"},
        "CHF": {"symbol": "CHF", "name": "Swiss Franc"},
        "SEK": {"symbol": "kr", "name": "Swedish Krona"},
        "NOK": {"symbol": "kr", "name": "Norwegian Krone"},
        "DKK": {"symbol": "kr", "name": "Danish Krone"},
        "ISK": {"symbol": "kr", "name": "Icelandic Krona"},
        "PLN": {"symbol": "zł", "name": "Polish Zloty"},
        "CZK": {"symbol": "Kč", "name": "Czech Koruna"},
        "HUF": {"symbol": "Ft", "name": "Hungarian Forint"},
        "RON": {"symbol": "lei", "name": "Romanian Leu"},
        "BGN": {"symbol": "лв", "name": "Bulgarian Lev"},
        "HRK": {"symbol": "kn", "name": "Croatian Kuna"},
        "RSD": {"symbol": "дин", "name": "Serbian Dinar"},
        "MKD": {"symbol": "ден", "name": "Macedonian Denar"},
        "ALL": {"symbol": "L", "name": "Albanian Lek"},
        "BAM": {"symbol": "КМ", "name": "Bosnia and Herzegovina Convertible Mark"},
        "MNT": {"symbol": "₮", "name": "Mongolian Tugrik"},
        "KZT": {"symbol": "₸", "name": "Kazakhstani Tenge"},
        "KGS": {"symbol": "лв", "name": "Kyrgyzstani Som"},
        "TJS": {"symbol": "ЅМ", "name": "Tajikistani Somoni"},
        "TMT": {"symbol": "T", "name": "Turkmenistani Manat"},
        "UZS": {"symbol": "лв", "name": "Uzbekistani Som"},
        "AFN": {"symbol": "؋", "name": "Afghan Afghani"},
        "PKR": {"symbol": "₨", "name": "Pakistani Rupee"},
        "BDT": {"symbol": "৳", "name": "Bangladeshi Taka"},
        "LKR": {"symbol": "₨", "name": "Sri Lankan Rupee"},
        "NPR": {"symbol": "₨", "name": "Nepalese Rupee"},
        "BTN": {"symbol": "Nu.", "name": "Bhutanese Ngultrum"},
        "MVR": {"symbol": "Rf", "name": "Maldivian Rufiyaa"},
        "SCR": {"symbol": "₨", "name": "Seychellois Rupee"},
        "MUR": {"symbol": "₨", "name": "Mauritian Rupee"},
        "KMF": {"symbol": "CF", "name": "Comorian Franc"},
        "DJF": {"symbol": "Fdj", "name": "Djiboutian Franc"},
        "ETB": {"symbol": "Br", "name": "Ethiopian Birr"},
        "KES": {"symbol": "KSh", "name": "Kenyan Shilling"},
        "TZS": {"symbol": "TSh", "name": "Tanzanian Shilling"},
        "UGX": {"symbol": "USh", "name": "Ugandan Shilling"},
        "RWF": {"symbol": "RF", "name": "Rwandan Franc"},
        "BIF": {"symbol": "FBu", "name": "Burundian Franc"},
        "MWK": {"symbol": "MK", "name": "Malawian Kwacha"},
        "ZMW": {"symbol": "ZK", "name": "Zambian Kwacha"},
        "BWP": {"symbol": "P", "name": "Botswana Pula"},
        "SZL": {"symbol": "L", "name": "Swazi Lilangeni"},
        "LSL": {"symbol": "L", "name": "Lesotho Loti"},
        "NAD": {"symbol": "N$", "name": "Namibian Dollar"},
        "MZN": {"symbol": "MT", "name": "Mozambican Metical"},
        "AOA": {"symbol": "Kz", "name": "Angolan Kwanza"},
        "XOF": {"symbol": "CFA", "name": "West African CFA Franc"},
        "XAF": {"symbol": "FCFA", "name": "Central African CFA Franc"},
        "CDF": {"symbol": "FC", "name": "Congolese Franc"},
        "GMD": {"symbol": "D", "name": "Gambian Dalasi"},
        "GHS": {"symbol": "₵", "name": "Ghanaian Cedi"},
        "GNF": {"symbol": "FG", "name": "Guinean Franc"},
        "LRD": {"symbol": "L$", "name": "Liberian Dollar"},
        "SLL": {"symbol": "Le", "name": "Sierra Leonean Leone"},
        "NGN": {"symbol": "₦", "name": "Nigerian Naira"},
        "TND": {"symbol": "د.ت", "name": "Tunisian Dinar"},
        "DZD": {"symbol": "د.ج", "name": "Algerian Dinar"},
        "MAD": {"symbol": "د.م.", "name": "Moroccan Dirham"},
        "LYD": {"symbol": "ل.د", "name": "Libyan Dinar"},
        "SDG": {"symbol": "ج.س.", "name": "Sudanese Pound"},
        "SSP": {"symbol": "£", "name": "South Sudanese Pound"},
        "SOS": {"symbol": "S", "name": "Somali Shilling"},
        "ERN": {"symbol": "Nfk", "name": "Eritrean Nakfa"},
        "SYP": {"symbol": "£", "name": "Syrian Pound"},
        "IQD": {"symbol": "ع.د", "name": "Iraqi Dinar"},
        "IRR": {"symbol": "﷼", "name": "Iranian Rial"},
        "YER": {"symbol": "﷼", "name": "Yemeni Rial"},
        "PAB": {"symbol": "B/.", "name": "Panamanian Balboa"},
        "CRC": {"symbol": "₡", "name": "Costa Rican Colón"},
        "GTQ": {"symbol": "Q", "name": "Guatemalan Quetzal"},
        "HNL": {"symbol": "L", "name": "Honduran Lempira"},
        "NIO": {"symbol": "C$", "name": "Nicaraguan Córdoba"},
        "SVC": {"symbol": "₡", "name": "Salvadoran Colón"},
        "BZD": {"symbol": "BZ$", "name": "Belize Dollar"},
        "JMD": {"symbol": "J$", "name": "Jamaican Dollar"},
        "TTD": {"symbol": "TT$", "name": "Trinidad and Tobago Dollar"},
        "BBD": {"symbol": "Bds$", "name": "Barbadian Dollar"},
        "XCD": {"symbol": "EC$", "name": "East Caribbean Dollar"},
        "AWG": {"symbol": "ƒ", "name": "Aruban Florin"},
        "ANG": {"symbol": "ƒ", "name": "Netherlands Antillean Guilder"},
        "SRD": {"symbol": "$", "name": "Surinamese Dollar"},
        "GYD": {"symbol": "G$", "name": "Guyanese Dollar"},
        "VES": {"symbol": "Bs.S", "name": "Venezuelan Bolívar"},
        "COP": {"symbol": "$", "name": "Colombian Peso"},
        "PEN": {"symbol": "S/", "name": "Peruvian Sol"},
        "BOB": {"symbol": "Bs", "name": "Bolivian Boliviano"},
        "CLP": {"symbol": "$", "name": "Chilean Peso"},
        "ARS": {"symbol": "$", "name": "Argentine Peso"},
        "UYU": {"symbol": "$U", "name": "Uruguayan Peso"},
        "PYG": {"symbol": "₲", "name": "Paraguayan Guarani"},
        "FKP": {"symbol": "£", "name": "Falkland Islands Pound"},
        "ISK": {"symbol": "kr", "name": "Icelandic Krona"},
        "RON": {"symbol": "lei", "name": "Romanian Leu"},
        "BGN": {"symbol": "лв", "name": "Bulgarian Lev"},
        "HRK": {"symbol": "kn", "name": "Croatian Kuna"},
        "RSD": {"symbol": "дин", "name": "Serbian Dinar"},
        "MKD": {"symbol": "ден", "name": "Macedonian Denar"},
        "ALL": {"symbol": "L", "name": "Albanian Lek"},
        "BAM": {"symbol": "КМ", "name": "Bosnia and Herzegovina Convertible Mark"}
    }