# Google Cloud Configuration
VERTEX_AI_PROJECT_ID="trip-planner-demo-471815"
VERTEX_AI_LOCATION="us-central1"
VERTEX_AI_MODEL="gemini-2.5-pro"



CLOUDSQL_CONNECTION_NAME="trip-planner-demo-471815:us-central1:wayfarer-postgresdb"
POSTGRES_DB="trip_planner"
POSTGRES_USER="trip_planner"
MYSQL_PASSWORD="Admin@123"


# Google OAuth Configuration
GOOGLE_CLIENT_ID="111720869272-q7kjecu971734jbp7i324sme6lrh61vk.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET="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"
GOOGLE_REDIRECT_URI="https://wayfarer-ai-github-111720869272.us-central1.run.app:8501"
GOOGLE_APPLICATION_CREDENTIALS="credentials/vertexAI.json"