# .streamlit/secrets.toml

VERTEX_AI_PROJECT_ID = "your-gcp-project-id"
VERTEX_AI_LOCATION = "your-vertex-location"
VERTEX_AI_MODEL = "your-vertex-model"

CLOUDSQL_CONNECTION_NAME = "your-cloudsql-connection-name"
POSTGRES_DB = "your-postgres-db-name"
POSTGRES_USER = "your-postgres-username"
MYSQL_PASSWORD = "your-mysql-password"

GOOGLE_CLIENT_ID = "your-google-client-id"
GOOGLE_CLIENT_SECRET = "your-google-client-secret"
GOOGLE_REDIRECT_URI = "http://localhost:8501"
GOOGLE_APPLICATION_CREDENTIALS = "credentials/vertexAI.json"
